data:
    dataset_type: "cached_threedfront"
    encoding_type: "cached_diffusion_cosin_angle_wocm" #"cached_diffusion_wocm_no_prm"
    dataset_directory: "/mnt/nas_3dv/hdd1/datasets/3D_FRONT_FUTURE/holistic_layout_20231113/threed_front_livingroom/"
    annotation_file: "config/livingroom_threed_front_splits.csv"
    path_to_invalid_scene_ids: "config/invalid_threed_front_rooms.txt"
    path_to_invalid_bbox_jids: "config/black_list.txt"
    augmentations: ["fixed_rotations"]
    filter_fn: "threed_front_livingroom" #"no_filtering"
    train_stats: "/mnt/nas_3dv/hdd1/datasets/3D_FRONT_FUTURE/holistic_layout_20231113/threed_front_livingroom/dataset_stats.txt"
    room_layout_size: "64,64"

training:
    splits: ["train", "val"]
    epochs: 60000
    steps_per_epoch: 500
    batch_size: 128
    save_frequency: 2000
    max_grad_norm: 10
    # optimizer
    optimizer: Adam
    weight_decay: 0.0
    # schedule
    schedule: 'step'
    lr: 0.0002
    lr_step: 10000
    lr_decay: 0.5

validation:
    splits: ["test"]
    frequency: 10
    batch_size: 128
    gen_traj: false
    num_step: 100
    gen_gt: false
    gen_prob_map: false
